.gitignore, .gitmodules, Gemfile, Gemfile.lock, PULL_REQUEST_TEMPLATE, README.md, _config.yml, _deconst.json, _posts/2018-05-04-Modern-supply-chain-made-simple-by-cloud-infrastructure.md, _posts/2018-08-29-applications-monitoring-creating-a-smoother-financial-close.md, _posts/2019-09-20-benefits-of-strategic-supply-chain-optimization.md
Removed rubyracer (Deconst dependency)
=> Get it to build locally

content/blog/2020/2020-08-01-snowflake-security-foundations/index.md
=> update snowflake post

Makefile, netlify.toml
Bug-fix release
https://github.com/gohugoio/hugo/releases
=> Update to Hugo 0.74.3 release

bioinfo.txt, content/blog/2020/2020-11-10-using-logstash-to-load-csv-data-into-elasticsearch/index.md
This has already been edited by Cat. The author's pic needed to be changed.
=> fixes author's pic

content/blog/2020/2020-11-11-optimizing-cloud-costs-with-spend-segmentation-and-chargeback/index.md
JIRA 6827
converting Onica blog "Optimizing cloud costs with spend segmentation and chargeback"
=> onica blog optimizing cloud costs

bioinfo.txt
=> add ross lawrie to bio page

bioinfo.txt, content/blog/2020/2020-11-24-enabling-remote-workforce-productivity-with-aws/index.md
HI @catlook Would you please review&edit this when you have a chance? Thank you!!!
=> updates bioinfo and modifies blogpost

content/blog/2020/2020-11-25-scaling-aws-for-black-friday-best-practices/index.md, content/blog/2020/2020-11-30-scaling-aws-for-black-friday-best-practices/index.md
JIRA 6890
Scaling AWS for Black Friday: Best practices blog migration
=> add onica blog aws scaling

bioinfo.txt, content/blog/2020/2020-12-01-leveraging-aws-to-prepare-your-ecommerce-platform-for-the-unexpected/index.md
JIRA 6885
Onica blog: Leveraging AWS to Prepare your eCommerce Platform for the Unexpected
=> Onica leveraging

content/blog/2020/2020-12-01-the-six-best-ways-to-reduce-costs-on-aws/index.md
Hi! @catlook Could you please review&edit this when you have a chance? Thank youuuu!!!
=> migrates Onica blog

content/blog/2020/2020-11-30-aws-systems-manager-run-command-simplifies-hybrid-cloud-management/index.md, content/blog/2020/2020-11-30-aws-systems-manager-run-command-simplify-hybrid-cloud-management/index.md
Hi! Would you please review&edit this when you have a chance?  Thank you!
=> migrates AWS systems manager blogpost

content/blog/2020/2020-12-07-from-datacenters-to-kubernetes-on-aws/index.md
Hi @catlook I know you're super busy, but could you please review & edit this when you have a chance? Thank you!
=> Kubernetes post

content/blog/2020/2020-12-08-cloud-migration-strategy-four-paths-to-consider-for-a-successful-move-to-the-cloud/index.md
Hi @catlook ! Would you please take a look at this when you have a chance? Thank youuuu
=> migrates blog -Cloud migration strategy

content/blog/2020/2020-12-08-why-aws-for-microsoft-workloads/index.md
Hi @catlook ! Would you review & edit this when you have a chance please? Thank you!
=> migrates blogpost

bioinfo.txt, content/blog/2020/2020-12-08-six-principles-to-be-successful-in-cloud-computing/index.md
Hi @catlook ! Would you please review & edit this when you have a chance? Thank you!
=> migrates blog and changes title

content/blog/2020/2020-12-10-meeting-security-compliance-on-aws/index.md
Hi @catlook Would you please review & edit this? Thank youuuu
=> migrates blog -security compliance

content/blog/2020/2020-12-10-migration-as-code-the-end-of-the-lift-and-shift-era/index.md
Hi @catlook ! Would you please review and edit this when you have a chance? Many thanks
=> creates migration as code blogpost

bioinfo.txt, content/blog/2020/2020-12-09-aws-container-services-how-does-it-work/index.md
Hi dear @catlook ! Would you please review and edit this when you have a chance? Thank you
=> AWS  container services

bioinfo.txt, content/blog/2020/2020-12-08-the-convergence-of-serverless-and-containers-on-aws/index.md
Hi @catlook I hope you're well. Is it ok if I send this review&edit your way?
=> The convergence

content/blog/2020/2020-12-11-the-value-of-joining-your-local-aws-meetup-group/index.md
Hi @stephamon Would you please review and edit this? Thank you
=> migrates blog

.github/dependabot.yml
=> Add Dependabot automated security update bot

content/blog/2020/2020-12-15-accelerate-your-business-with-iot/index.md
Hi @catlook Would you please review and edit this PR? Thank you
=> creates blog

content/blog/2020/2020-12-15-accelerate-your-business-with-iot/index.md
Hi @catlook ! Here's the fix =)
=> updates title

content/blog/2020/2020-12-16-kibana-default-index-pattern/index.md
JIRA 7027
How-To: Kibana Default Index Pattern
=> Onica kibana

CONTRIBUTING.md
This revised version conforms closely to the corresponding file in the How-To repo.
=> update and standardize process and procedures

content/blog/2020/2020-12-17-getting-the-cloud-right-aws-well-architected-framework/index.md
Hi @stephamon , could you please review and edit this when you have a chance? Thank you!
=> Add new blog: Getting the cloud right

content/blog/2020/2020-12-21-how-to-deploy-docker-on-aws-whitepaper/index.md
Hi @stephamon ! Could you please review and edit this? Thank you!
=> Add new blog: How to deploy Docker on AWS whitepaper

content/blog/2020/2020-12-21-why-companies-are-turning-to-aws-managed-services/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? Thank you
=> Add new blog: Companies are turning to AWS

content/blog/2020/2020-12-22-when-to-use-elastic-beanstalk-custom-ami-versus-standard-ami/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? Thank you!
=> Add new blog: When to use Elastic Beanstalk

bioinfo.txt, content/blog/2020/2020-12-23-restore-oracle-database-using-rman-duplicate-in-oracle-12c/index.md
JIRA 6992
Creating new blog from the RAS team about RMAN and databases.
=> new tricore blog

content/blog/2020/2020-12-28-deep-dive-on-amazon-aurora/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? Thank you =)
=> Add new blog: Deep dive on Amazon Aurora

content/blog/2020/2020-12-29-aws-benefits-why-should-you-consider-migrating/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? Thank you!
=> Add blog: AWS benefits: Why should you consider migrating?

content/blog/2020/2020-12-28-scaling-windows-workloads-in-aws/index.md
Hi @stephamon , could you please review and edit this when you get a chance? Thanks!
=> Add new blog: Scaling Windows workloads in AWS

content/blog/2021/2021-01-04-introduction-to-amazon-textract/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? Thank you
=> Add blog: Introduction to Amazon Textract

content/blog/2020/2020-08-18-rackspace-technology-makes-network-security-a-reality/index.md
Hi @stephamon ! Could you please review this? The author's avatar link was broken and author doesn't have a usable pic on slack. I'll reach out to him after the holidays and see if he has another option.
=> Deletes author avatar, broken link, will ask author for pic

content/blog/2020/2020-10-27-postgres-backups-and-how-to-restore-them-on-object-rocket/index.md
Hi @stephamon , I found another title that needed a tiny cosmetic change, and I also changed line 32, it read: "Rackspace ObjectRocket", and I decided to change it to "ObjectRocket, a Rackspace Technology company" just to keep it consistent with what we've been doing in other blogposts. Could you please review it, and edit it if needed? Thank you.
=> Changes capitalization in title, tiny cosmetic change

content/blog/2020/2020-11-25-a-guide-to-customizing-the-customer-journey-with-amazon-personalize/index.md
Hi @stephamon ! Could you please review and edit this when you have a chance? I changed the capitalization in the previous title. I wasn't satisfied with it.
=> Changes capitalization of title

content/blog/2021/2021-01-04-what-are-the-benefits-of-a-devops-culture/index.md
Hi @catlook ! Would you please review and edit this when you have a chance? Thank you
=> Add blog: What are the benefits of a DevOps culture?

content/blog/2021/2021-01-04-getting-started-with-the-aws-hipaa-quick-start/index.md
Hi @catlook ! Would you please review and edit this when you have a chance? Thank you!
=> Add blog: Getting started with AWS HIPAA QuickStart

content/blog/2021/2021-01-05-basic-aws-security-principles/index.md
Hi @catlook ! Could you please take a look at this when you have a chance?
=> Add new blog: Basic AWS security principles

content/blog/2021/2021-01-06-increasing-the-bottom-line-by-diversifying-it-with-aws/index.md
Hi @catlook ! Would you please review and edit this PR when you have a chance? Thank you
=> Add blog: Increasing the bottom line by diversifying IT with AWS

content/blog/2021/2021-01-07-tolga-talks-tech-moving-up-the-stack-on-aws/index.md
Hi @catlook ! Could you please review and edit this when you have a chance? Thank you
=> Add blog: Tolga talks tech: Moving up the stack in AWS

content/blog/2021/2021-01-06-how-to-achieve-hipaa-compliance-in-aws/index.md
Hi @catlook , could you please review and edit this when you have a chance? Thank you
=> Add new blog: How to achieve HIPAA in AWS

content/blog/2021/2021-01-08-how-to-use-the-appdeploy-filesystem-hook/index.md
Hi @catlook ! Could you please review an edit this PR when you have a chance? Thank you
=> Add blog: How to use Appdeploy Filesystems hook

content/blog/2021/2021-01-12-how-to-call-and-export-environment-variables-in-aws-elastic-beanstalk/index.md
Hi @catlook ! Could you please review and edit this PR when you have a chance? Thank you
=> Add blog: How to call environment variables in AWS Elastic Beanstalk

bioinfo.txt, content/blog/2021/2021-01-12-using-spot-instances-with-kubernetes-kops/index.md
Hi @catlook ! Could you please review and edit this PR when you have a chance? Thank you!
=> Add blog: Using spot instances with Kubernetes' kops

content/blog/2021/2021-01-20-do-not-let-your-website-crash-on-black-friday-or-ever/index.md
Hi @catlook ! Could you please review and edit this PR when you get a chance? Thank you!
=> Add blog: Do not let your website crash on Black Friday or ever

content/blog/2021/2021-01-19-viewing-your-world-through-security-colored-devops-glasses/index.md
Hi @catlook ! Could you please review and edit this PR when you get a chance? Thank you =)
=> Add blog: Viewing your world through Security colored DevOps glasses

content/blog/2021/2021-01-21-four-aws-multi-region-architecture-considerations/index.md
Hi @catlook Would you please review and edit this when you get a chance? Thank you!!!
=> Add blog: Four AWS multi-region architecture considerations

content/blog/2021/2021-01-25-revisiting-amazon-web-services-web-application-firewall-aws-waf/index.md
Hi! Could you review and edit this PR when you have a chance? Thank you!
=> Add blog: Revisiting AWS WAF

content/blog/2021/2021-09-23-cloning-a-database-using-the-database-configuration-assistant-dbca-in-Oracle-19-c/index.md
removed source reference. Changed upper and lower cases in some sentences
=> minor tweaks in the capitalization and structure of the blog post

content/blog/2021/2021-11-09-configure-tde-with-always-on-availability-group/index.md
Reverts rackerlabs/technical-blog#712
=> Revert "Update index.md"

content/blog/2022/2022-05-17-basics-of-hashicorp-vagrant/index.md, content/blog/2022/2022-05-24-creating-a-kubernetes-cluster-on-aws-eks/index.md, content/blog/2022/2022-06-02-configuration-of-oracle-e-business-suite-enterprise-command-centers-ecc/index.md
Fixed code blocks in 3 more pages:
* https://docs.rackspace.com/blog/configuration-of-oracle-e-business-suite-enterprise-command-centers-ecc/
* https://docs.rackspace.com/blog/creating-a-kubernetes-cluster-on-aws-eks/
* https://docs.rackspace.com/blog/basics-of-hashicorp-vagrant/
=> fixed 3 more pages

content/blog/2023/2023-02-10-vmware-esxi-cve-2021-21974/index.md
This request will post a blog article for a new vmware cve to docs.rack
=> Add vmware cve blog post

content/blog/2023/2023-02-15-rackspace-response-to-f5-security-advisory/index.md
New request for Marc Nourani for F5 Security article.
Original content provided here: https://raxglobal.sharepoint.com/:w:/r/sites/IM/Shared%20Documents/Incidents/Cisco%20F5%20Vulnerabilities%20Feb%202023/Communications/F5%20Feb%202023%20Blog%20Post.docx?d=w4aede847f51c4a5db9cd8ec93ec9a463&csf=1&web=1&e=e7U3j9
=> Response to F5 Security Advisory

content/blog/2023/2023-02-15-rackspace-response-to-f5-security-advisory/index.md
business provided found an issue with our described update process.
=> Correction to update process

content/blog/2023/2023-02-16-rackspace-response-to-february-2023-microsoft-patch/index.md
Article requested by Carl James about Rackspace Response to Feb. 2023 Microsoft Patch.
Original content was provided at this link.
https://raxglobal-my.sharepoint.com/:w:/r/personal/eric_zuniga_rackspace_com/Documents/Microsoft%20Teams%20Chat%20Files/MSFT%20Patch%20Vulnerability%20Feb%202023%20Blog%20Post.docx?d=w353555b7542848ecb9c932c7a41e3478&csf=1&web=1&e=4jjFud
=> Rackspace response to feb 2023 microsoft patch

content/blog/2023/2023-03-16-rackspace-response-to-march-2023-microsoft-patch-tuesday-security-advisory/index.md
Adding March 2023 Patch Tuesday blog article as requested by Marc Nourani today at 4:30pm March 16, 2023.
=> Rackspace response to march 2023 microsoft patch
